"""One-time, idempotent transfer of the production SQLite database to Postgres."""
from __future__ import annotations

import re
import sqlite3
from pathlib import Path

import psycopg
from psycopg import sql


def _postgres_ddl(statement: str) -> str:
    value = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        statement,
        flags=re.IGNORECASE,
    )
    return re.sub(r"\bBLOB\b", "BYTEA", value, flags=re.IGNORECASE)


def migrate_sqlite_to_postgres(sqlite_path: Path, database_url: str) -> dict[str, int]:
    """Copy schema, data and sequences once; fail rather than overwrite data."""
    source = sqlite3.connect(sqlite_path)
    source.row_factory = sqlite3.Row
    try:
        schema_rows = source.execute(
            "SELECT type, name, tbl_name, sql FROM sqlite_master "
            "WHERE type IN ('table', 'index') AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL "
            "ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name"
        ).fetchall()
        tables = [row for row in schema_rows if row["type"] == "table"]
        indexes = [row for row in schema_rows if row["type"] == "index"]
        with psycopg.connect(database_url) as target:
            with target.cursor() as cursor:
                cursor.execute("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'")
                existing = int(cursor.fetchone()[0])
                if existing:
                    raise RuntimeError("Postgres is not empty; refusing to overwrite an existing database.")
                for row in tables:
                    cursor.execute(_postgres_ddl(str(row["sql"])))

                copied_rows = 0
                for row in tables:
                    table = str(row["name"])
                    data = source.execute(f'SELECT * FROM "{table}"').fetchall()
                    if not data:
                        continue
                    columns = list(data[0].keys())
                    statement = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
                        sql.Identifier(table),
                        sql.SQL(", ").join(map(sql.Identifier, columns)),
                        sql.SQL(", ").join(sql.Placeholder() for _ in columns),
                    )
                    cursor.executemany(statement, [tuple(item[column] for column in columns) for item in data])
                    copied_rows += len(data)
                    if "id" in columns:
                        cursor.execute(
                            sql.SQL("SELECT setval(pg_get_serial_sequence({}, 'id'), COALESCE((SELECT MAX(id) FROM {}), 1), true)").format(
                                sql.Literal(table), sql.Identifier(table)
                            )
                        )

                for row in indexes:
                    cursor.execute(_postgres_ddl(str(row["sql"])))
        return {"tables": len(tables), "rows": copied_rows}
    finally:
        source.close()
